### ISSUE TITLE
Вопрос про вертикальный размер панелей

### ISSUE THREAD

**Issue by smithx** [aborodin/midnight-widgets#1]
Добрый день, не нашёл ваш контакт, чтобы спросить в личку. Я не знаком с программированием консольных интерфейсов в Linux - не понимаю "физику" ограничения. В mc в настройках Layout можно задать количество видимых строк консоли, не закрытых панелями. Но эта функциональность работает только в "raw" терминалах. В KDE Konsole, например, она не активна. Существуют ли какие-то "препядтсвия непреодолимой силы" (в разумных пределах, конечно), чтобы реализовать этот же функционал, условно говоря, для `mc_global.tty.console_flag == '\0' ` ? 
Буду очень признателен, если скажите, что почитать по теме. Спасибо.

**Comment by aborodin** [comment]
Здравствуйте.
Мой контакт есть в коммитах во From и Signed-off-by.
Боюсь, на ваш вопрос у меня нет ответа. Я тоже не всё знаю. Есть места в mc, в которые мне не хочется лишний раз лезть. Работает -- и ладно. Вот это как раз тот случай.

**Comment by smithx** [comment]
Спасибо )
